# Generated by Django 4.2.1 on 2023-06-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="код")),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                ("file", models.FileField(upload_to="", verbose_name="файл")),
            ],
            options={
                "verbose_name": "учебный план",
                "verbose_name_plural": "учебные планы",
            },
        ),
    ]
